In [1]:
import numpy as np

In [3]:
np.outer(np.array([1,2,3]), np.array([1,2,3]))

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [6]:
X = np.array([[1,2,3,4],[1,2,3,4]])
np.mean(X, axis=1)

array([2.5, 2.5])

In [5]:
print(X)

[[1 2 3 4]
 [1 2 3 4]]
